### PR TITLE
Allow 0 values by filtering empty string and nulls

### PR DESCRIPTION
**Pull request by garcia-al**

### CODE REVIEW

**Comment by garcia-al** [comment]
@gpou This changes the behaviour for non required fields, to allow 0 values to be validated. When moving validation from the listing to the monetary_information, none of the validations were running for 0 values, cause of the line I changed.
So we will still skip empty string and null values, but the 0 is a value that we do want to validate in our code.

Not sure how circle works in these repos, says it is not setup.

**Comment by bboure** [comment]
@garcia-al  Looks like there is a Travis setup but I guess we need to give Travis access to our repo or something like that...

**Comment by bboure** [comment]
@garcia-al Do all **our** circle tests pass with this change ?

**Comment by garcia-al** [comment]
@bboure Did not check yet, I was fixing the tests I know I was going to break, but will be hard to run all test on local :D

**Comment by brutuscat** [comment]
@garcia-al `trim("$value")` might also cut it!

**Pull request merged**
